<?php
	$web = new web((object) array(
		"level" => "100",
		"model" => "user",
		"control" => "user",
		"title" => "Users"
	));
?>

<div class="p-6 bg-white border-b border-gray-200 mx-auto max-w-screen-xl">

	<div class="flex items-center justify-between">
		<h1 class="text-2xl font-semibold text-gray-900">Users</h1>
		<a href="/user" class="relative inline-flex items-center px-4 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-300 rounded-md shadow-sm hover:bg-gray-50">New User</a>
	</div>

	<ul role="list" class="mt-5 divide-y divide-gray-100">
		<? foreach ($users as $user) { ?>
			<li>
				<a href="/user/<?=$user->id?>" class="flex px-5 justify-between gap-x-6 py-5 hover:bg-gray-200">
					<div class="flex min-w-0 gap-x-4">
						<div class="flex w-12 h-12 text-sm bg-gray-400 rounded-full md:me-0 focus:ring-4 focus:ring-gray-300 dark:focus:ring-gray-600">
							<img class="w-12 h-12 rounded-full" src="/img/default-user.svg" alt="user photo">
						</div>
						<div class="min-w-0 flex-auto">
							<p class="text-sm font-semibold leading-6 text-gray-900"><?= $user->name ?></p>
							<p class="mt-1 truncate text-xs leading-5 text-gray-500"><?= $user->email ?></p>
						</div>
					</div>
					<div class="hidden shrink-0 sm:flex sm:flex-col sm:items-end">
						<p class="text-sm leading-6 text-gray-900">
							<?= $web->db->queryUniqueValue("SELECT name FROM sp_level WHERE id = ".$user->level) ?>
						</p>
					</div>
				</a>
			</li>
		<? } ?>
	</ul>

	<? $web->pagination($web->user); ?>

</div>