<?php
$web = new web((object) array(
	"level" => "100",
	"title" => "Users"
));
?>

<div class="p-6 bg-white border-b border-gray-200 mx-auto max-w-screen-xl">

	<form>
		<div class="space-y-12">
			<div class="border-b border-gray-900/10 pb-12">

				<h2 class="text-4xl font-semibold leading-7 text-gray-900">Perfil</h2>

				<div class="mt-10 grid grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-6">
					<div class="sm:col-span-4">
						<label for="username" class="block text-sm font-medium leading-6 text-gray-900">Username</label>
						<div class="mt-2">
							<div class="flex rounded-md shadow-sm ring-1 ring-inset ring-gray-300 focus-within:ring-2 focus-within:ring-inset focus-within:ring-indigo-600 sm:max-w-md">
								<input type="text" name="username" id="username" autocomplete="username" class="block flex-1 border-0 bg-transparent py-1.5 pl-1 text-gray-900 placeholder:text-gray-400 focus:ring-0 sm:text-sm sm:leading-6" placeholder="janesmith" disabled>
							</div>
						</div>
					</div>

					<div class="sm:col-span-4">
						<label for="name" class="block text-sm font-medium leading-6 text-gray-900">Nombre</label>
						<div class="mt-2">
							<div class="flex rounded-md shadow-sm ring-1 ring-inset ring-gray-300 focus-within:ring-2 focus-within:ring-inset focus-within:ring-indigo-600 sm:max-w-md">
								<input type="text" name="name" id="name" autocomplete="name" class="block flex-1 border-0 bg-transparent py-1.5 pl-1 text-gray-900 placeholder:text-gray-400 focus:ring-0 sm:text-sm sm:leading-6" placeholder="Jane Smith">
							</div>
						</div>
					</div>

					<div class="sm:col-span-4">
						<label for="email" class="block text-sm font-medium leading-6 text-gray-900">E-mail</label>
						<div class="mt-2">
							<div class="flex rounded-md shadow-sm ring-1 ring-inset ring-gray-300 focus-within:ring-2 focus-within:ring-inset focus-within:ring-indigo-600 sm:max-w-md">
								<input type="text" name="email" id="email" autocomplete="email" class="block flex-1 border-0 bg-transparent py-1.5 pl-1 text-gray-900 placeholder:text-gray-400 focus:ring-0 sm:text-sm sm:leading-6" placeholder="email@domain.com">
							</div>
						</div>
					</div>

					<div class="sm:col-span-4">
						<label for="permisions" class="block text-sm font-medium leading-6 text-gray-900">Permisos</label>
						<div class="mt-2">
							<div class="flex rounded-md shadow-sm ring-1 ring-inset ring-gray-300 focus-within:ring-2 focus-within:ring-inset focus-within:ring-indigo-600 sm:max-w-md">
								<select id="countries" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
									<option value="100">Administrador</option>
									<option value="50">RRSS</option>
									<option value="40">Diseño</option>
									<option value="10">Cliente</option>
								</select>
							</div>
						</div>
					</div>

					<div class="col-span-full">
						<label for="photo" class="block text-sm font-medium leading-6 text-gray-900">Foto</label>
						<div class="mt-2 flex items-center gap-x-3">
							<svg class="h-12 w-12 text-gray-300" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true">
								<path fill-rule="evenodd" d="M18.685 19.097A9.723 9.723 0 0021.75 12c0-5.385-4.365-9.75-9.75-9.75S2.25 6.615 2.25 12a9.723 9.723 0 003.065 7.097A9.716 9.716 0 0012 21.75a9.716 9.716 0 006.685-2.653zm-12.54-1.285A7.486 7.486 0 0112 15a7.486 7.486 0 015.855 2.812A8.224 8.224 0 0112 20.25a8.224 8.224 0 01-5.855-2.438zM15.75 9a3.75 3.75 0 11-7.5 0 3.75 3.75 0 017.5 0z" clip-rule="evenodd" />
							</svg>
							<button type="button" class="rounded-md bg-white px-2.5 py-1.5 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50">Change</button>
						</div>
					</div>

				</div>
			</div>

		</div>

		<div class="mt-6 flex items-center justify-end gap-x-6">
			<button type="button" class="cancel-btn text-sm font-semibold leading-6 text-gray-900">Cancel</button>
			<button type="submit" class="rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Save</button>
		</div>
	</form>

</div>