<?php 
	$web = new web((object) array(	"level" => "100",
									"title" => "Users" )); 
?>

<div class="p-6 bg-white border-b border-gray-200 mx-auto max-w-screen-xl">
		
	<div class="flex items-center justify-between">
	<h1 class="text-2xl font-semibold text-gray-900">Users</h1>
	<a href="/user" class="relative inline-flex items-center px-4 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-300 rounded-md shadow-sm hover:bg-gray-50">New User</a>
	</div>

	<ul role="list" class="divide-y divide-gray-100">
	<li class="flex justify-between gap-x-6 py-5">
		<div class="flex min-w-0 gap-x-4">
		<img class="h-12 w-12 flex-none rounded-full bg-gray-50" src="https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="">
		<div class="min-w-0 flex-auto">
			<p class="text-sm font-semibold leading-6 text-gray-900">Leslie Alexander</p>
			<p class="mt-1 truncate text-xs leading-5 text-gray-500">leslie.alexander@example.com</p>
		</div>
		</div>
		<div class="hidden shrink-0 sm:flex sm:flex-col sm:items-end">
		<p class="text-sm leading-6 text-gray-900">Co-Founder / CEO</p>
		<p class="mt-1 text-xs leading-5 text-gray-500">Last seen <time datetime="2023-01-23T13:23Z">3h ago</time></p>
		</div>
	</li>
	<li class="flex justify-between gap-x-6 py-5">
		<div class="flex min-w-0 gap-x-4">
		<img class="h-12 w-12 flex-none rounded-full bg-gray-50" src="https://images.unsplash.com/photo-1519244703995-f4e0f30006d5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="">
		<div class="min-w-0 flex-auto">
			<p class="text-sm font-semibold leading-6 text-gray-900">Michael Foster</p>
			<p class="mt-1 truncate text-xs leading-5 text-gray-500">michael.foster@example.com</p>
		</div>
		</div>
		<div class="hidden shrink-0 sm:flex sm:flex-col sm:items-end">
		<p class="text-sm leading-6 text-gray-900">Co-Founder / CTO</p>
		<p class="mt-1 text-xs leading-5 text-gray-500">Last seen <time datetime="2023-01-23T13:23Z">3h ago</time></p>
		</div>
	</li>
	<li class="flex justify-between gap-x-6 py-5">
		<div class="flex min-w-0 gap-x-4">
		<img class="h-12 w-12 flex-none rounded-full bg-gray-50" src="https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="">
		<div class="min-w-0 flex-auto">
			<p class="text-sm font-semibold leading-6 text-gray-900">Dries Vincent</p>
			<p class="mt-1 truncate text-xs leading-5 text-gray-500">dries.vincent@example.com</p>
		</div>
		</div>
		<div class="hidden shrink-0 sm:flex sm:flex-col sm:items-end">
		<p class="text-sm leading-6 text-gray-900">Business Relations</p>
		<div class="mt-1 flex items-center gap-x-1.5">
			<div class="flex-none rounded-full bg-emerald-500/20 p-1">
			<div class="h-1.5 w-1.5 rounded-full bg-emerald-500"></div>
			</div>
			<p class="text-xs leading-5 text-gray-500">Online</p>
		</div>
		</div>
	</li>
	<li class="flex justify-between gap-x-6 py-5">
		<div class="flex min-w-0 gap-x-4">
		<img class="h-12 w-12 flex-none rounded-full bg-gray-50" src="https://images.unsplash.com/photo-1517841905240-472988babdf9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="">
		<div class="min-w-0 flex-auto">
			<p class="text-sm font-semibold leading-6 text-gray-900">Lindsay Walton</p>
			<p class="mt-1 truncate text-xs leading-5 text-gray-500">lindsay.walton@example.com</p>
		</div>
		</div>
		<div class="hidden shrink-0 sm:flex sm:flex-col sm:items-end">
		<p class="text-sm leading-6 text-gray-900">Front-end Developer</p>
		<p class="mt-1 text-xs leading-5 text-gray-500">Last seen <time datetime="2023-01-23T13:23Z">3h ago</time></p>
		</div>
	</li>
	<li class="flex justify-between gap-x-6 py-5">
		<div class="flex min-w-0 gap-x-4">
		<img class="h-12 w-12 flex-none rounded-full bg-gray-50" src="https://images.unsplash.com/photo-1438761681033-6461ffad8d80?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="">
		<div class="min-w-0 flex-auto">
			<p class="text-sm font-semibold leading-6 text-gray-900">Courtney Henry</p>
			<p class="mt-1 truncate text-xs leading-5 text-gray-500">courtney.henry@example.com</p>
		</div>
		</div>
		<div class="hidden shrink-0 sm:flex sm:flex-col sm:items-end">
		<p class="text-sm leading-6 text-gray-900">Designer</p>
		<p class="mt-1 text-xs leading-5 text-gray-500">Last seen <time datetime="2023-01-23T13:23Z">3h ago</time></p>
		</div>
	</li>
	<li class="flex justify-between gap-x-6 py-5">
		<div class="flex min-w-0 gap-x-4">
		<img class="h-12 w-12 flex-none rounded-full bg-gray-50" src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="">
		<div class="min-w-0 flex-auto">
			<p class="text-sm font-semibold leading-6 text-gray-900">Tom Cook</p>
			<p class="mt-1 truncate text-xs leading-5 text-gray-500">tom.cook@example.com</p>
		</div>
		</div>
		<div class="hidden shrink-0 sm:flex sm:flex-col sm:items-end">
		<p class="text-sm leading-6 text-gray-900">Director of Product</p>
		<div class="mt-1 flex items-center gap-x-1.5">
			<div class="flex-none rounded-full bg-emerald-500/20 p-1">
			<div class="h-1.5 w-1.5 rounded-full bg-emerald-500"></div>
			</div>
			<p class="text-xs leading-5 text-gray-500">Online</p>
		</div>
		</div>
	</li>
	</ul>


	<div class="flex items-center justify-between border-t border-gray-200 bg-white px-4 py-3 sm:px-6">
	<div class="flex flex-1 justify-between sm:hidden">
		<a href="#" class="relative inline-flex items-center rounded-md border border-gray-300 bg-white px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50">Previous</a>
		<a href="#" class="relative ml-3 inline-flex items-center rounded-md border border-gray-300 bg-white px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50">Next</a>
	</div>
	<div class="hidden sm:flex sm:flex-1 sm:items-center sm:justify-between">
		<div>
		<p class="text-sm text-gray-700">
			Showing
			<span class="font-medium">1</span>
			to
			<span class="font-medium">10</span>
			of
			<span class="font-medium">97</span>
			results
		</p>
		</div>
		<div>
		<nav class="isolate inline-flex -space-x-px rounded-md shadow-sm" aria-label="Pagination">
			<a href="#" class="relative inline-flex items-center rounded-l-md px-2 py-2 text-gray-400 ring-1 ring-inset ring-gray-300 hover:bg-gray-50 focus:z-20 focus:outline-offset-0">
			<span class="sr-only">Previous</span>
			<svg class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
				<path fill-rule="evenodd" d="M12.79 5.23a.75.75 0 01-.02 1.06L8.832 10l3.938 3.71a.75.75 0 11-1.04 1.08l-4.5-4.25a.75.75 0 010-1.08l4.5-4.25a.75.75 0 011.06.02z" clip-rule="evenodd" />
			</svg>
			</a>
			<!-- Current: "z-10 bg-indigo-600 text-white focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600", Default: "text-gray-900 ring-1 ring-inset ring-gray-300 hover:bg-gray-50 focus:outline-offset-0" -->
			<a href="#" aria-current="page" class="relative z-10 inline-flex items-center bg-indigo-600 px-4 py-2 text-sm font-semibold text-white focus:z-20 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">1</a>
			<a href="#" class="relative inline-flex items-center px-4 py-2 text-sm font-semibold text-gray-900 ring-1 ring-inset ring-gray-300 hover:bg-gray-50 focus:z-20 focus:outline-offset-0">2</a>
			<a href="#" class="relative hidden items-center px-4 py-2 text-sm font-semibold text-gray-900 ring-1 ring-inset ring-gray-300 hover:bg-gray-50 focus:z-20 focus:outline-offset-0 md:inline-flex">3</a>
			<span class="relative inline-flex items-center px-4 py-2 text-sm font-semibold text-gray-700 ring-1 ring-inset ring-gray-300 focus:outline-offset-0">...</span>
			<a href="#" class="relative hidden items-center px-4 py-2 text-sm font-semibold text-gray-900 ring-1 ring-inset ring-gray-300 hover:bg-gray-50 focus:z-20 focus:outline-offset-0 md:inline-flex">8</a>
			<a href="#" class="relative inline-flex items-center px-4 py-2 text-sm font-semibold text-gray-900 ring-1 ring-inset ring-gray-300 hover:bg-gray-50 focus:z-20 focus:outline-offset-0">9</a>
			<a href="#" class="relative inline-flex items-center px-4 py-2 text-sm font-semibold text-gray-900 ring-1 ring-inset ring-gray-300 hover:bg-gray-50 focus:z-20 focus:outline-offset-0">10</a>
			<a href="#" class="relative inline-flex items-center rounded-r-md px-2 py-2 text-gray-400 ring-1 ring-inset ring-gray-300 hover:bg-gray-50 focus:z-20 focus:outline-offset-0">
			<span class="sr-only">Next</span>
			<svg class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
				<path fill-rule="evenodd" d="M7.21 14.77a.75.75 0 01.02-1.06L11.168 10 7.23 6.29a.75.75 0 111.04-1.08l4.5 4.25a.75.75 0 010 1.08l-4.5 4.25a.75.75 0 01-1.06-.02z" clip-rule="evenodd" />
			</svg>
			</a>
		</nav>
		</div>
	</div>
	</div>

</div>