<?php
	$web = new web((object) array(
		"level" => "100",
		"model" => "user",
		"control" => "user",
		"title" => "Users"
	));
?>

<div class="p-6 bg-white border-b border-gray-200 mx-auto max-w-screen-xl">

	<div class="flex items-center justify-between">
		<h1 class="text-2xl font-semibold text-gray-900">Users</h1>
		<a href="/user" class="relative inline-flex items-center px-4 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-300 rounded-md shadow-sm hover:bg-gray-50">New User</a>
	</div>

	<ul role="list" class="divide-y divide-gray-100">
		<? foreach ($users as $user) { ?>
			<li class="flex justify-between gap-x-6 py-5">
				<div class="flex min-w-0 gap-x-4">
					<img class="h-12 w-12 flex-none rounded-full bg-gray-50" src="https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="">
					<div class="min-w-0 flex-auto">
						<p class="text-sm font-semibold leading-6 text-gray-900"><?= $user->name ?></p>
						<p class="mt-1 truncate text-xs leading-5 text-gray-500"><?= $user->email ?></p>
					</div>
				</div>
				<div class="hidden shrink-0 sm:flex sm:flex-col sm:items-end">
					<p class="text-sm leading-6 text-gray-900"><?= $user->level ?></p>
				</div>
			</li>
		<? } ?>
	</ul>

	<? $web->pagination($web->user); ?>

</div>