<?php

	if( $_POST['webAction'] == "" ) {
		$_POST['webAction'] = "get";
		$_POST['id'] = $_GET['val1'];
	}

	$web = new web((object) array(
		"level" => "100",
		"title" => "Users",
		"model" => "user",
		"control" => "user"
	));

?>

<div class="p-6 bg-white border-b border-gray-200 mx-auto max-w-screen-xl">

	<?php 
		if(isset($web->user->error)) {
			foreach($web->user->error as $error) {
				echo '<div class="mb-10 bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" role="alert"><strong class="font-bold">Error:</strong><span class="block">'.$web->user->error_messages[$error].'</span></div>';
			}
		} 
	?>

	<form action="/user/<?=$user->id?>" enctype="multipart/form-data" method="post" id="main-form" autocomplete="off">

		<div class="space-y-12">
			<div class="border-b border-gray-900/10 pb-12">

				<h2 class="text-4xl font-semibold leading-7 text-gray-900">Perfil</h2>

				<div class="mt-10 grid grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-6">
					<div class="sm:col-span-4">
						<label for="user" class="block text-sm font-medium leading-6 text-gray-900">Username</label>
						<div class="mt-2">
							<div class="flex rounded-md shadow-sm ring-1 ring-inset ring-gray-300 focus-within:ring-2 focus-within:ring-inset focus-within:ring-indigo-600 sm:max-w-md">
								<input value="<?=$user->user?>" type="text" name="user" id="user" autocomplete="nope" class="block flex-1 border-0 bg-transparent py-1.5 pl-1 text-gray-900 placeholder:text-gray-400 focus:ring-0 sm:text-sm sm:leading-6" placeholder="janesmith" required>
							</div>
						</div>
					</div>

					<div class="sm:col-span-4">
						<label for="name" class="block text-sm font-medium leading-6 text-gray-900">Nombre</label>
						<div class="mt-2">
							<div class="flex rounded-md shadow-sm ring-1 ring-inset ring-gray-300 focus-within:ring-2 focus-within:ring-inset focus-within:ring-indigo-600 sm:max-w-md">
								<input value="<?=$user->name?>" type="text" name="name" id="name" class="block flex-1 border-0 bg-transparent py-1.5 pl-1 text-gray-900 placeholder:text-gray-400 focus:ring-0 sm:text-sm sm:leading-6" placeholder="Jane Smith" required>
							</div>
						</div>
					</div>

					<div class="sm:col-span-4">
						<label for="email" class="block text-sm font-medium leading-6 text-gray-900">E-mail</label>
						<div class="mt-2">
							<div class="flex rounded-md shadow-sm ring-1 ring-inset ring-gray-300 focus-within:ring-2 focus-within:ring-inset focus-within:ring-indigo-600 sm:max-w-md">
								<input value="<?=$user->email?>" type="email" name="email" id="email" class="block flex-1 border-0 bg-transparent py-1.5 pl-1 text-gray-900 placeholder:text-gray-400 focus:ring-0 sm:text-sm sm:leading-6" placeholder="email@domain.com" required>
							</div>
						</div>
					</div>

					<div class="sm:col-span-4">
						<label for="pass" class="block text-sm font-medium leading-6 text-gray-900">Password</label>
						<div class="mt-2">
							<div class="flex rounded-md shadow-sm ring-1 ring-inset ring-gray-300 focus-within:ring-2 focus-within:ring-inset focus-within:ring-indigo-600 sm:max-w-md">
								<input value="" type="password" name="pass" id="pass" autocomplete="new-pass" class="block flex-1 border-0 bg-transparent py-1.5 pl-1 text-gray-900 placeholder:text-gray-400 focus:ring-0 sm:text-sm sm:leading-6">
							</div>
						</div>
					</div>

					<div class="sm:col-span-4">
						<label for="permisions" class="block text-sm font-medium leading-6 text-gray-900">Permisos</label>
						<div class="mt-2">
							<div class="flex rounded-md shadow-sm ring-1 ring-inset ring-gray-300 focus-within:ring-2 focus-within:ring-inset focus-within:ring-indigo-600 sm:max-w-md">
								<select name="level" id="level" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
									<option value="100" <?=$web->INPUT_selected($user->level, "100") ?>>Administrador</option>
									<option value="50" <?=$web->INPUT_selected($user->level, "50") ?>>RRSS</option>
									<option value="40" <?=$web->INPUT_selected($user->level, "40") ?>>Diseño</option>
									<option value="10" <?=$web->INPUT_selected($user->level, "10") ?>>Cliente</option>
								</select>
							</div>
						</div>
					</div>
<!--
					<div class="col-span-full">
						<label for="photo" class="block text-sm font-medium leading-6 text-gray-900">Foto</label>
						<div class="mt-2 flex items-center gap-x-3">
							<button type="button" class="flex text-sm bg-gray-400 rounded-full md:me-0 focus:ring-4 focus:ring-gray-300 dark:focus:ring-gray-600" id="user-photo-button">
								<img class="w-8 h-8 rounded-full" src="/img/default-user.svg" alt="user photo">
							</button>
							<button type="button" class="rounded-md bg-white px-2.5 py-1.5 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50">Change</button>
						</div>
					</div>
-->
				</div>
			</div>

		</div>

		<input type="hidden" id="id" name="id" value="<?=$user->id?>" />
		<input type="hidden" id="webObject" name="webObject" value="user" />
		<input type="hidden" id="webAction" name="webAction" value="<?php echo $web->webAction?>" />

		<div class="mt-6 flex items-center justify-end gap-x-6">
			<a href="/users" class="text-sm font-semibold leading-6 text-gray-900">Cancel</a>
			<button type="submit" class="rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Save</button>
		</div>
	</form>

</div>