<?php 
	$web = new web((object) array(	"level" => "100",
									"title" => "Workspaces" )); 
?>
<div class="p-6 bg-white border-b border-gray-200 mx-auto max-w-screen-xl">
		
		<div class="flex items-center justify-between">
			<h1 class="text-2xl font-semibold text-gray-900">Workspaces</h1>
			<a href="#" class="relative inline-flex items-center px-4 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-300 rounded-md shadow-sm hover:bg-gray-50">New Workspace</a>
		</div>
	
		<div class="container my-12 mx-auto px-4 md:px-12">
			<div class="flex flex-wrap -mx-1 lg:-mx-4">
	
				<!-- Column -->
				<div class="my-1 px-1 w-full md:w-1/2 lg:my-4 lg:px-4 lg:w-1/3">
	
					<!-- Article -->
					<article class="overflow-hidden rounded-lg shadow-lg">
	
						<a href="#">
							<img alt="Placeholder" class="block h-auto w-full" src="https://picsum.photos/600/400/?random">
						</a>
	
						<header class="flex items-center justify-between leading-tight p-2 md:p-4">
							<h1 class="text-lg">
								<a class="no-underline hover:underline text-black" href="#">
									Article Title
								</a>
							</h1>
							<p class="text-grey-darker text-sm">
								11/1/19
							</p>
						</header>
	
						<footer class="flex items-center justify-between leading-none p-2 md:p-4">
							<a class="flex items-center no-underline hover:underline text-black" href="#">
								<img alt="Placeholder" class="block rounded-full" src="https://picsum.photos/32/32/?random">
								<p class="ml-2 text-sm">
									Author Name
								</p>
							</a>
							<a class="no-underline text-grey-darker hover:text-red-dark" href="#">
								<span class="hidden">Like</span>
								<i class="fa fa-heart"></i>
							</a>
						</footer>
	
					</article>
					<!-- END Article -->
	
				</div>
				<!-- END Column -->
	
				<!-- Column -->
				<div class="my-1 px-1 w-full md:w-1/2 lg:my-4 lg:px-4 lg:w-1/3">
	
					<!-- Article -->
					<article class="overflow-hidden rounded-lg shadow-lg">
	
						<a href="#">
							<img alt="Placeholder" class="block h-auto w-full" src="https://picsum.photos/600/400/?random">
						</a>
	
						<header class="flex items-center justify-between leading-tight p-2 md:p-4">
							<h1 class="text-lg">
								<a class="no-underline hover:underline text-black" href="#">
									Article Title
								</a>
							</h1>
							<p class="text-grey-darker text-sm">
								11/1/19
							</p>
						</header>
	
						<footer class="flex items-center justify-between leading-none p-2 md:p-4">
							<a class="flex items-center no-underline hover:underline text-black" href="#">
								<img alt="Placeholder" class="block rounded-full" src="https://picsum.photos/32/32/?random">
								<p class="ml-2 text-sm">
									Author Name
								</p>
							</a>
							<a class="no-underline text-grey-darker hover:text-red-dark" href="#">
								<span class="hidden">Like</span>
								<i class="fa fa-heart"></i>
							</a>
						</footer>
	
					</article>
					<!-- END Article -->
	
				</div>
				<!-- END Column -->
	
				<!-- Column -->
				<div class="my-1 px-1 w-full md:w-1/2 lg:my-4 lg:px-4 lg:w-1/3">
	
					<!-- Article -->
					<article class="overflow-hidden rounded-lg shadow-lg">
	
						<a href="#">
							<img alt="Placeholder" class="block h-auto w-full" src="https://picsum.photos/600/400/?random">
						</a>
	
						<header class="flex items-center justify-between leading-tight p-2 md:p-4">
							<h1 class="text-lg">
								<a class="no-underline hover:underline text-black" href="#">
									Article Title
								</a>
							</h1>
							<p class="text-grey-darker text-sm">
								11/1/19
							</p>
						</header>
	
						<footer class="flex items-center justify-between leading-none p-2 md:p-4">
							<a class="flex items-center no-underline hover:underline text-black" href="#">
								<img alt="Placeholder" class="block rounded-full" src="https://picsum.photos/32/32/?random">
								<p class="ml-2 text-sm">
									Author Name
								</p>
							</a>
							<a class="no-underline text-grey-darker hover:text-red-dark" href="#">
								<span class="hidden">Like</span>
								<i class="fa fa-heart"></i>
							</a>
						</footer>
	
					</article>
					<!-- END Article -->
	
				</div>
				<!-- END Column -->
	
				<!-- Column -->
				<div class="my-1 px-1 w-full md:w-1/2 lg:my-4 lg:px-4 lg:w-1/3">
	
					<!-- Article -->
					<article class="overflow-hidden rounded-lg shadow-lg">
	
						<a href="#">
							<img alt="Placeholder" class="block h-auto w-full" src="https://picsum.photos/600/400/?random">
						</a>
	
						<header class="flex items-center justify-between leading-tight p-2 md:p-4">
							<h1 class="text-lg">
								<a class="no-underline hover:underline text-black" href="#">
									Article Title
								</a>
							</h1>
							<p class="text-grey-darker text-sm">
								11/1/19
							</p>
						</header>
	
						<footer class="flex items-center justify-between leading-none p-2 md:p-4">
							<a class="flex items-center no-underline hover:underline text-black" href="#">
								<img alt="Placeholder" class="block rounded-full" src="https://picsum.photos/32/32/?random">
								<p class="ml-2 text-sm">
									Author Name
								</p>
							</a>
							<a class="no-underline text-grey-darker hover:text-red-dark" href="#">
								<span class="hidden">Like</span>
								<i class="fa fa-heart"></i>
							</a>
						</footer>
	
					</article>
					<!-- END Article -->
	
				</div>
				<!-- END Column -->
	
				<!-- Column -->
				<div class="my-1 px-1 w-full md:w-1/2 lg:my-4 lg:px-4 lg:w-1/3">
	
					<!-- Article -->
					<article class="overflow-hidden rounded-lg shadow-lg">
	
						<a href="#">
							<img alt="Placeholder" class="block h-auto w-full" src="https://picsum.photos/600/400/?random">
						</a>
	
						<header class="flex items-center justify-between leading-tight p-2 md:p-4">
							<h1 class="text-lg">
								<a class="no-underline hover:underline text-black" href="#">
									Article Title
								</a>
							</h1>
							<p class="text-grey-darker text-sm">
								11/1/19
							</p>
						</header>
	
						<footer class="flex items-center justify-between leading-none p-2 md:p-4">
							<a class="flex items-center no-underline hover:underline text-black" href="#">
								<img alt="Placeholder" class="block rounded-full" src="https://picsum.photos/32/32/?random">
								<p class="ml-2 text-sm">
									Author Name
								</p>
							</a>
							<a class="no-underline text-grey-darker hover:text-red-dark" href="#">
								<span class="hidden">Like</span>
								<i class="fa fa-heart"></i>
							</a>
						</footer>
	
					</article>
					<!-- END Article -->
	
				</div>
				<!-- END Column -->
	
				<!-- Column -->
				<div class="my-1 px-1 w-full md:w-1/2 lg:my-4 lg:px-4 lg:w-1/3">
	
					<!-- Article -->
					<article class="overflow-hidden rounded-lg shadow-lg">
	
						<a href="#">
							<img alt="Placeholder" class="block h-auto w-full" src="https://picsum.photos/600/400/?random">
						</a>
	
						<header class="flex items-center justify-between leading-tight p-2 md:p-4">
							<h1 class="text-lg">
								<a class="no-underline hover:underline text-black" href="#">
									Article Title
								</a>
							</h1>
							<p class="text-grey-darker text-sm">
								11/1/19
							</p>
						</header>
	
						<footer class="flex items-center justify-between leading-none p-2 md:p-4">
							<a class="flex items-center no-underline hover:underline text-black" href="#">
								<img alt="Placeholder" class="block rounded-full" src="https://picsum.photos/32/32/?random">
								<p class="ml-2 text-sm">
									Author Name
								</p>
							</a>
							<a class="no-underline text-grey-darker hover:text-red-dark" href="#">
								<span class="hidden">Like</span>
								<i class="fa fa-heart"></i>
							</a>
						</footer>
	
					</article>
					<!-- END Article -->
	
				</div>
				<!-- END Column -->
	
			</div>
		</div>
	
	</div>