<!DOCTYPE html>
<html lang="<?php echo $this->language ?>">

<head>

	<meta charset="<?php echo $this->charset ?>"> 
	<meta http-equiv="content-language" content="<?php echo $this->language ?>">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<meta http-equiv="Cache-control" content="public">
	
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1">
	<meta name="keywords" content="<?php echo $this->meta_keywords ?>" />
	<meta name="abstract" content="<?php echo $this->meta_description ?>" />
	<meta name="description" content="<?php echo $this->meta_description ?>" />

	<title><?php echo  $this->full_title ?></title>

	<link rel="shortcut icon" href="/img/logo.svg" type="image/x-icon" />

	<link rel="stylesheet" type="text/css" href="/css/website-styles.css"/>
	<link rel="stylesheet" type="text/css" href="/css/tailwind-output.css"/>

	<script src="/js/functions.js" type="text/javascript"></script>

	<?php echo $this->head ?>
	
</head>

<body>

	<? $this->layout('header') ?>

	<div id="main">

		<?php echo $this->content ?>

	</div>

	<script src="https://unpkg.com/@themesberg/flowbite@latest/dist/flowbite.bundle.js"></script>
	
</body>

</html>